name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest
      options: --cap-add SYS_ADMIN --security-opt apparmor=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          set -e
          ln -snf "$GITHUB_WORKSPACE" /workdir
          # the entrypoint is rewritten so we need to launch searchd manually
          searchd
          cd /workdir
          composer install --prefer-dist
          git clone https://github.com/manticoresoftware/phar_builder.git
          bin/test

  buddy-test:
    name: Run buddy tests
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest
      options: --cap-add SYS_ADMIN --security-opt apparmor=unconfined

    steps:
      - name: Run buddy tests
        run: |
          set -e
          git clone https://github.com/manticoresoftware/manticoresearch-buddy.git /workdir
          cd /workdir

          PACKAGE=${{ github.repository }}
          BRANCH=${{ github.head_ref || github.ref_name }}

          composer install --prefer-source

          cd vendor/$PACKAGE
          git fetch
          git checkout $BRANCH
          cd /workdir

          git clone https://github.com/manticoresoftware/phar_builder.git

          searchd
          bin/test

  codestyle:
    name: PHPCS validation
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PHPCS to check following the standard
        run: |
          set -e
          ln -snf "$GITHUB_WORKSPACE" /workdir
          cd /workdir
          composer install --prefer-dist
          bin/codestyle

  codeanalyze:
    name: PHPStan static analysis
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PHPStan to analyze the codebase
        run: |
          set -e
          ln -snf "$GITHUB_WORKSPACE" /workdir
          cd /workdir
          composer install --prefer-dist
          bin/codeanalyze
