name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest
      options: --cap-add SYS_ADMIN --security-opt apparmor=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run doctum
        run: |
          set -e
          ln -snf "$GITHUB_WORKSPACE" /workdir
          cd /workdir
          composer require --dev code-lts/doctum -W
          vendor/bin/doctum.php update config/doctum.php --ignore-parse-errors
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
