name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run doctum inside docker container
        uses: manticoresoftware/addnab-docker-run-action@v3
        with:
          image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir --cap-add SYS_ADMIN --security-opt apparmor=unconfined
          run: |
            composer require --dev code-lts/doctum
            vendor/bin/doctum.php update config/doctum.php --ignore-parse-errors
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
